### ISSUE TITLE
Title blinking

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/Facebook-Messenger-Desktop#150]
in first launch the app title on taskbar was changing "facebook" and "messenger" in really short intervals, so i seen just blinking. After restart no issue

**Comment by radnor** [comment]
This might be resolved by modifying `window-behaviour.js` so that the `parentDoc.title` is changed only if the `childDoc.title` is different. Right now it's resetting `parentDoc.title` every 100 ms.

Increasing the timeout to 1000 ms would probably be a good idea too. :smile: 

https://github.com/Aluxian/Facebook-Messenger-Desktop/blob/e7b7e4e88aaa38114da971e61543a7d88ccdff44/src/components/window-behaviour.js#L107

**Comment by jackwebster** [comment]
Issue continues, but still only on first launch (win32, built today)

**Comment by Sytten** [comment]
Issue resolved in the current beta.
Please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
