### ISSUE TITLE
Voice calls don't work

### ISSUE THREAD

**Issue by 6uui** [Aluxian/Facebook-Messenger-Desktop#333]
Voice calls don't work, only at the website, which is really stupid.
![screenshot_20160124175546](https://cloud.githubusercontent.com/assets/16867021/12537929/15e598bc-c2c4-11e5-98ee-82732c6419ce.png)
![screenshot_20160124175827](https://cloud.githubusercontent.com/assets/16867021/12537930/16ef5932-c2c4-11e5-96be-2b9b14178cd0.png)

**Comment by NitsuSaiNeko** [comment]
The voice call will pop up in a browser, but it works. It's only annoying when my friend calls me, I hit answer and the browser popped up asking me if I want to call, which on my friend's side, I neither hanged up nor answered it, which I can't call him since his literally "on the phone".
I wonder if it is possible to just pick up the phone within the messenger or have a specific pop out windows in Messenger for Desktop style that answers the phone instead of opening using browser.

**Comment by Sytten** [comment]
Yes that will be resolved in the next beta, the problem lie in the setting: Open links in browser
Meanwhile please see https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/458
