### ISSUE TITLE
online contacts list needed

### ISSUE THREAD

**Issue by transgressor01** [Aluxian/Facebook-Messenger-Desktop#346]
add the feature of **online contacts** list

**Comment by NitsuSaiNeko** [comment]
I didn't get it. There's contacts list already and you can tell if they're online by the icon right under their avatar.

**Comment by transgressor01** [comment]
what I meant was the feature like appearance of a green dot in front of the online contact

**Comment by Gittyperson** [comment]
A helpful addition would be the ability to sort contacts by their online status, and/or only show online contacts.

What Facebook considers "online" still confuses me though, since I see much more 'online' users (blue icon) in your excellent Messenger on Windows 10, than in the Facebook webpage on my browser.

**Comment by Sytten** [comment]
Not relevant, closing
