### ISSUE TITLE
Notifications are not showing up on linux

### ISSUE THREAD

**Issue by Sytten** [Aluxian/Facebook-Messenger-Desktop#421]
We are suppose to have removed the native notifications for the Chrome notifications, but their are not showing up on linux. 
Their is only the odd blinking icon (we should avoir blinking too, that would be great).

**Comment by nevercast** [comment]
I made no changes to notifications in the source. But they have changed with the new version of nwjs. 

Being a Chrome App now, we no longer have access to Native notifications. With that said, it doesn't HAVE to be that way. We can depend on a library on the Node.JS side and create native notifications that way.

Thoughts?

**Comment by Sytten** [comment]
Chrome notifications are nice, if we can make them work that would be good for the current release.
Native notifications are sometime better, but not always. I would not bother investigating that way though.

**Comment by rikai** [comment]
I will say that as a user, at least on windows, i would much prefer chrome notifications, because the notification system in windows is ugly and leaves a lot to be desired functionality-wise.

On other platforms, i would likely prefer native notifications for integration reasons(mac, Notification Center) or extensibility reasons(linux, inline replies in notifications(!?)) , so perhaps in a later release an option between chrome & native notifications could be considered?

**Comment by Sytten** [comment]
I totally agree with you! We will do our best to provide that feature :)

**Comment by pyrforos** [comment]
I would like to  have notifications from  system because  it is more customizable. For example  the option to  run  a command (in linux/kde) is very useful for a visual alert  like a  blinking led  for a new message (with the help of an arduino) :) 
Just a suggestion

**Comment by Sytten** [comment]
With the new version of nw.js I currently can't provide the old system of native notification. I will have to add a plugin to do that. Maybe in the next version if possible.

**Comment by Sytten** [comment]
Not an issue anymore
