### ISSUE TITLE
Group Calling isn't an option.

### ISSUE THREAD

**Issue by Skurrow** [Aluxian/Facebook-Messenger-Desktop#471]
To be honest, the only reason I downloaded this app was because I hoped that like the app for mobile, it'd allow me to host a group call. However it does not. Would really love to see it introduced ASAP. Will not be using the app until it does.

**Comment by Sytten** [comment]
To be honest, your attitude makes me want to close your issue ASAP.
Please note that we provide free work and if you are not satisfied you can help instead of complaining.

As for the request, you must first understand that we are only a wrapper around messenger.com. All the features provided by messenger.com are in the app. I never tested group calls myself but I don't see why it would not work out of the box.
