### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Saqibkazmi** [Aluxian/Facebook-Messenger-Desktop#52]
I love the idea and app. Its great.
I am sure you will improve it further but I have some suggestions. Please consider them in next version:
1. Make the window of messenger's UI border less on Windows OS.
2. Ability to make contact list to dock/pinned on right or left side of screen (as on Facebook).
3. Ability to show/hide the chat by adding a little arrow button. like I have made in picture.
Thanks.
![messea](https://cloud.githubusercontent.com/assets/12114796/7334129/f61640ac-eba2-11e4-8d67-0be75f8ec183.PNG)

**Comment by Aluxian** [comment]
1. I don't want to remove the borders because I'd have to manually create a title bar for each platform. In Windows 10 the app will look better: http://inft.ly/3mbnH3k
2. Pinning the app is not possible with nw.js (by pinning, I mean pinning it in a native way with the platform's window manager). However, you can resize it and move it to the side of your screen yourself.
3. Although I don't like this behaviour, this might happen when/if I implement this: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/55
